name = "simple-iot-cloud-website"
main = "workers/worker.js"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "ee86c1206b9f46ad3fe92ed714954932"
workers_dev = true

kv_namespaces = [
  { binding = "SENSOR_DATA", id = "2d731617cf1f4ac196756a02f246a38b" }
]

